config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get  'home/show'
  resources :articles
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!,only: [:new,:create,:edit,:destroy]
  before_action :correct_user,      only: [:edit, :destroy]
  
  def show
    @article = Article.find(params[:id])
    
    REDIS.zincrby "articles/pv", 1, @article.id
    
    ids = REDIS.zrevrangebyscore "articles/pv", "inf", 0, limit:[0, 3], :with_scores => true
    @ids=[]
    @scores=[]       
    
    ids.each do |id, score|
      @ids << id
      @scores << score.to_i
    end
    
    @ranking_articles = @ids.map{|id|Article.find(id)}
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:notice] = "Article created!"
      redirect_to root_url
    else
      render new_article_path
      flash[:alert]= "Invalid Post"
    end
  end
  
  def edit
  end
  
  def update
    @article = Article.find(params[:id])
      if @article.update(article_params)
        redirect_to root_url
        flash[:notice]= "Article Edited!"
      else
        redirect_to request.referer
        flash[:alert]= "Invalid Post"
      end
  end
  
  def destroy
    @article.destroy 
    flash[:notice] = "Article destroyed"
    REDIS.zrem "articles/pv", params[:id]
    redirect_to root_url
  end
  
  private
  
    def article_params
      params.require(:article).permit(:title, :content)
    end
    
    def correct_user
      @article = current_user.articles.find_by(id: params[:id])
      if @article.nil?
        redirect_to root_url 
        flash[:notice] = "Not Yours"
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @articles = Article.all
    
    ids = REDIS.zrevrangebyscore "articles/pv", "inf", 0, limit:[0, 3], :with_scores => true
    @ids=[]
    @scores=[]       
    
    ids.each do |id, score|
      @ids << id
      @scores << score.to_i
    end
    
    @ranking_articles = @ids.map{| id |Article.find(id)}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<div>
    <h2> <%= link_to article.title, article_path(article.id) %> </h2>
    <p> <%= article.created_at.strftime('%Y/%m/%d') %> </p>
    <p>
        <% if user_signed_in? %>
            <%= link_to '編集', edit_article_path(article.id) %>
            <%= link_to '削除', article_path(article.id), method: :delete %>
        <% end %>    
            
    </p>    
</div>

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <div class="field">
    <%= f.text_area :title, :placeholder =>"#{@article.title}" %>
  </div>  
  <div class="field">
    <%= f.text_area :content, :placeholder =>"#{@article.content}" %>
  </div>      
    <%= f.submit "投稿を更新", class:"btn btn-primary" %>
<% end %>

app/views/articles/new.html.erb
<%= form_for(@article) do |f|%>
  <div class="field">
    <%= f.text_area :title, placeholder:"タイトル" %>
  </div>  
  <div class="field">
    <%= f.text_area :content, placeholder:"記事内容" %>
  </div>
  <%= f.submit"Post", class: "btn btn-primary" %>
<% end %>

app/views/articles/show.html.erb
<div id="title">
    <div>
        <p> <%= @article.created_at.strftime('%Y/%m/%d') %> 投稿者:<%= @article.user.email %></p>
        <h1><%= @article.title%></h1>
    </div>
</div>    
<%= render 'shared/ranking' %>
<div id="article_wrap">
    <%= @article.content %>
</div>

<div class="clear"></div> 

app/views/devises/shared/_error_messages.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/devises/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/home/index.html.erb
<div id="main">
      <img src="/assets/main-img.jpg" />
    </div>
    <%= render 'shared/ranking' %>
    <div id="article_wrap">
        <div id="article_list">
            <%= render @articles %>
        </div> 
        
        <div class="clear"></div>    
    </div> 

app/views/layouts/_footer.html.erb
<div id="footer_inner">
    <p>Copyright RailsCamp 2015 All Rights Reserved</p>
</div>

app/views/layouts/_header.html.erb
<p id="logo">
　<a href="https://baseconnect.herokuapp.com/">RailsCamp<span>Blog</span></a></p>
    <nav>
        <ul>
            <% if user_signed_in? %>
                <li><%= link_to 'トップ', root_path %></li>
                <li><%= link_to '新規投稿', new_article_path %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to '新規登録', new_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>
        </ul>
    </nav>
    <div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/toast'%>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_ranking.html.erb
<div id="sidebar">
    <h2>★PV数ランキング</h2>
    <ul>
        <% @ranking_articles.zip(@scores) do |article,score| %>
         <li>
             <%= link_to(article.title,"/articles/#{article.id}") %>
             <span>
                 <%= score %>PV
             </span>
         </li>    
        <% end %>
          

</div>

app/views/shared/_toast.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> 